/** Reviewed English catalog. Chinese source keys are intentional and stay stable for the default UI. */
export const englishMessages: Readonly<Record<string, string>> = {
  '设置自动保存；数字输入按 Enter 或点击其他位置生效。': 'Settings are saved automatically. Press Enter or click elsewhere to apply a number.',
  '只调整正文文字，不改变按钮和设置面板。': 'Changes document text without resizing buttons or settings.',
  '正文区域的最大宽度，包含左右留白。窗口较窄时自动缩小。': 'Maximum document area width, including side padding. It shrinks to fit narrow windows.',
  '一起缩放正文、按钮和设置面板。不改变导出内容和系统菜单。': 'Scales document text, buttons and settings together. Exports and system menus keep their size.',
  '在正文上方显示加粗、标题、列表等常用按钮。': 'Shows common formatting buttons above the document, including bold, headings and lists.',
  '侧栏与预览': 'Sidebar and preview',
  '拖动面板之间的分隔线调整大小，双击恢复默认比例。': 'Drag a divider to resize panels. Double-click to restore the default size.',
  '窗口变窄时，侧栏会覆盖正文，点击正文即可关闭；源码与预览会自动上下排列。': 'In narrow windows, the sidebar overlays the document. Click outside to close it. Source and preview stack vertically.',
  '尺寸快捷键': 'Size shortcuts',
  '正文：Ctrl+Alt+加号 / 减号，Ctrl+Alt+0 恢复。界面：Ctrl+加号 / 减号，Ctrl+0 恢复。': 'Text: Ctrl+Alt+plus / minus; Ctrl+Alt+0 resets it. Interface: Ctrl+plus / minus; Ctrl+0 resets it.',
  '分隔线可用方向键调整，按住 Shift 加大步幅，Enter 恢复。': 'Use arrow keys on a divider to resize. Hold Shift for larger steps; Enter resets it.',
  '正文排版': 'Document typography',
  '倍': '×', '空格': 'spaces', '秒': 's',
  '相邻两行的间距。1.8 表示字号的 1.8 倍。': 'Distance between lines. 1.8 means 1.8 times the text size.',
  '阅读字体（宋体风格）': 'Reading (serif)',
  '简洁字体（黑体风格）': 'Simple (sans serif)',
  '等宽字体（适合代码）': 'Monospace (for code)',
  '源码编辑': 'Source editing',
  '源码显示 Markdown 标记，适合直接修改格式。': 'Source mode shows Markdown syntax so you can edit formatting directly.',
  '按 Tab 键时的缩进大小，也用于代码块。': 'Indentation added by Tab. Also used in code blocks.',
  '智能标点只作用于新输入的正文，不会批量改写已有内容。代码、公式和文档信息保持原样。': 'Smart punctuation applies to newly typed text. Existing content, code, math and document metadata remain unchanged.',
  '按需开启额外格式；关闭后仍保留文档中的原始文字。': 'Enable extra formats as needed. Turning them off keeps the original document text.',
  '查看格式写法': 'Show syntax examples',
  '只自动保存已有文件名的文档。未保存的内容会保留恢复副本。': 'Only named files are saved automatically. Unsaved content is kept in recovery copies.',
  '文件被其他程序修改时，自动保存会暂停，并提醒你处理。': 'If another program changes the file, automatic saving pauses and you are prompted to resolve it.',
  '使用文档信息中的标题和作者': 'Use the title and author from document metadata',
  '文档信息写在文件开头的两条 --- 之间，也称 Front Matter。': 'Document metadata is written between two --- lines at the start of the file, also called Front Matter.',
  'PDF 内容与纸张边缘之间的留白。': 'Space between PDF content and the edges of the page.',
  '高级选项：用 CSS 修改正文样式，并用于带样式的导出。不熟悉 CSS 时可以留空。': 'Advanced: customize document and styled export appearance with CSS. Leave blank if you do not use CSS.',
  '布局与尺寸': 'Layout and size',
  '布局与尺寸…': 'Layout and size…',
  '重置布局与尺寸': 'Reset layout and size',
  '面板': 'Panels',
  '界面缩放（%）': 'Interface zoom (%)',
  '显示格式工具栏': 'Show formatting toolbar',
  '切换格式工具栏': 'Toggle formatting toolbar',
  '恢复面板默认尺寸': 'Reset panel sizes',
  '增大正文字号': 'Increase text size',
  '减小正文字号': 'Decrease text size',
  '恢复正文字号': 'Reset text size',
  '恢复界面缩放': 'Reset interface zoom',
  '放大界面': 'Zoom in interface',
  '缩小界面': 'Zoom out interface',
  '调整侧栏宽度': 'Resize sidebar',
  '调整源码与预览比例': 'Resize source and preview',
  '紧凑': 'Compact',
  '舒适': 'Comfortable',
  '宽屏': 'Wide',
  '字号只改变正文；Ctrl+Alt+加号 / 减号调整，Ctrl+Alt+0 恢复。': 'Text size changes only document text. Use Ctrl+Alt+plus / minus to adjust, Ctrl+Alt+0 to reset.',
  '正文宽度是最大值（像素），窗口变窄时自动收缩。': 'Document width is a maximum in pixels. It shrinks automatically in narrower windows.',
  '界面缩放同时改变菜单控件和正文的显示大小，不影响导出。Ctrl+加号 / 减号调整，Ctrl+0 恢复。': 'Interface zoom changes controls and text on screen without affecting exports. Use Ctrl+plus / minus to adjust, Ctrl+0 to reset.',
  '拖动侧栏或源码与预览之间的分隔线调整宽度；双击恢复。分隔线也支持方向键，Enter 恢复。': 'Drag the sidebar or source/preview divider to resize; double-click to reset. Arrow keys also resize, Enter resets.',
  '窄窗口中侧栏覆盖正文，点击正文区域关闭；并排预览自动改为上下排列，放大窗口后恢复。': 'In narrow windows, the sidebar overlays the document; click outside to close. Split preview stacks vertically and returns side by side when the window grows.',
  '界面缩放改变所有控件的显示大小；字号只改变正文，正文宽度是最大值。': 'Interface zoom resizes all controls; text size changes only document text, and document width is a maximum.',
  '复制选区为 Markdown': 'Copy selection as Markdown',
  '复制选区为 HTML': 'Copy selection as HTML',
  '复制选区为纯文本': 'Copy selection as plain text',
  '请先在文档中选择内容。': 'Select content in the document first.',
  '选区已失效，请重新选择。': 'The selection is no longer current. Select it again.',
  '此选区暂不支持格式复制；表格矩形请使用 Ctrl+C。': 'This selection cannot be copied in an explicit format yet. Use Ctrl+C for a table rectangle.',
  '选区包含暂不支持保真复制的内容。': 'The selection contains content that cannot be copied without loss yet.',
  '选区超过剪贴板大小限制。': 'The selection exceeds the clipboard size limit.',
  '已复制选区': 'Selection copied',
  '已复制选区（部分图片为引用说明）': 'Selection copied; some images are reference labels',
  '帮助': 'Help',
  '关于 Penlume': 'About Penlume',
  '版本 {value1}': 'Version {value1}',
  '确定': 'OK',
  '筛选标题': 'Filter headings',
  '筛选标题…': 'Filter headings…',
  '平铺大纲': 'Flat outline',
  '折叠 {value1}': 'Collapse {value1}',
  '展开 {value1}': 'Expand {value1}',
  '匹配标题的上级': 'Parent of a matching heading',
  '没有匹配的标题。': 'No matching headings.',
  '当前层级没有标题。': 'No headings at this depth.',
  '筛选显示全部层级，清空后恢复。': 'Filtering shows all heading levels; clear the filter to restore the depth.',
  '空标题': 'Untitled heading',
  '正在更新大纲…': 'Updating outline…',
  '大纲暂不可用': 'Outline temporarily unavailable',
  '文档已关闭，请重新打开后插入资源。': 'The document is closed. Reopen it before inserting resources.',
  '资源路径已变化，请重试。': 'The resource path changed. Try again.',
  '文档尚未保存，不能访问本地图片。': 'Save the document before accessing local images.',
  '不支持当前平台之外的图片路径。': 'Image paths from another platform are not supported.',
  '无法生成图片引用。': 'Unable to generate an image reference.',
  '图片路径或资源根设置无效或不受支持。': 'The image path or resource root setting is invalid or unsupported.',
  '文档尚未保存，不能访问本地媒体。': 'Save the document before accessing local media.',
  '不支持当前平台之外的媒体路径。': 'Media paths from another platform are not supported.',
  '无法生成媒体引用。': 'Unable to generate a media reference.',
  '媒体路径或资源根设置无效或不受支持。': 'The media path or resource root setting is invalid or unsupported.',
  '文档路径须为本机绝对路径。': 'The document path must be an absolute path on this platform.',
  '文档的图片资源根不受支持。': 'The document image resource root is not supported.',
  '图片路径或编码不受支持。': 'The image path or encoding is not supported.',
  '引用检查不完整（资源根或路径不受支持、读取失败、符号链接或超出扫描上限），已禁止移入恢复区。': 'Reference checks are incomplete because of an unsupported root or path, a read failure, a symbolic link, or a scan limit. Moving assets to recovery is disabled.',
  '无法在当前图片资源根下生成指向目标的引用，已取消文件复制。': 'Unable to reference the destination from the current image resource root. File copying was cancelled.',
  '文档的图片资源根或保存位置已改变，请重新上传并检查结果。': 'The document image resource root or save location changed. Upload again and review the results.',
  '文档的保存位置在上传后改变，请重新上传并检查结果。': 'The document save location changed after uploading. Upload again and review the results.',
  '表格剪贴板内容超过支持的大小。': 'The table clipboard contents exceed the supported size.',
  '表格剪贴板文本的引号或行列结构不完整。': 'The table clipboard text has invalid quotes or an irregular grid.',
  '此表格剪贴板结构暂不支持，文档内容保持原样。': 'This table clipboard structure is not supported. The document is unchanged.',
  '界面语言': 'Interface language',
  '界面': 'Interface',
  '实时切换界面语言，不修改文档内容和文件名。': 'Changes the interface immediately. Document contents and filenames stay as written.',
  '简体中文': 'Simplified Chinese',
  '未命名文档': 'Untitled document',
  '文件': 'File', '编辑': 'Edit', '格式': 'Format', '视图': 'View', '写作': 'Write', '搜索': 'Search', '设置': 'Settings',
  '新建': 'New', '新建文档': 'New document', '新建文件夹': 'New folder', '新建文档（Ctrl+N）': 'New document (Ctrl+N)',
  '打开': 'Open', '打开…': 'Open…', '打开文档': 'Open document', '打开 Markdown 文件': 'Open Markdown file',
  '打开文件夹': 'Open folder', '打开文件夹…': 'Open folder…', 'Markdown 与文本': 'Markdown and text',
  '关闭': 'Close', '关闭文档': 'Close document', '关闭当前文档': 'Close current document', '关闭文档（Ctrl+W）': 'Close document (Ctrl+W)',
  '关闭 {value1}': 'Close {value1}', '关闭错误': 'Dismiss error', '打开的文档': 'Open documents',
  '保存': 'Save', '保存文档': 'Save document', '保存全部': 'Save all', '保存全部文档': 'Save all documents',
  '另存为': 'Save as', '另存为…': 'Save as…', '另存为 Markdown 文件': 'Save Markdown file as',
  '撤销': 'Undo', '重做': 'Redo', '撤销（Ctrl+Z）': 'Undo (Ctrl+Z)', '重做（Ctrl+Y）': 'Redo (Ctrl+Y)',
  '剪切': 'Cut', '复制': 'Copy', '粘贴': 'Paste', '全选': 'Select all',
  '复制文档为 Markdown': 'Copy document as Markdown', '复制文档为 HTML': 'Copy document as HTML', '复制文档为纯文本': 'Copy document as plain text',
  '复制文档为 ': 'Copy document as ', '复制文档为 {format}': 'Copy document as {format}',
  '纯文本': 'Plain text', 'PNG 图片': 'PNG image', '无样式 HTML': 'Unstyled HTML',
  '导出': 'Export', '导出 ': 'Export ', '导出 {format}': 'Export {format}', '导出文档': 'Export document',
  '导出为 HTML': 'Export as HTML', '导出为 HTML…': 'Export as HTML…', '导出为 PDF': 'Export as PDF', '导出为 PDF…': 'Export as PDF…',
  '导出为 PNG': 'Export as PNG', '导出为 PNG 图片…': 'Export as PNG image…', '导出无样式 HTML…': 'Export unstyled HTML…',
  '文档转换 / 导入': 'Convert / import documents', '文档转换 / 导入…': 'Convert / import documents…', '退出': 'Quit',
  '偏好设置': 'Preferences', '偏好设置…': 'Preferences…', '恢复默认设置': 'Restore defaults', '完成': 'Done',
  '编辑器': 'Editor', '字号': 'Font size', '行高': 'Line height', '正文宽度': 'Content width', '字体': 'Font',
  '衬线字体': 'Serif', '无衬线字体': 'Sans serif', '等宽字体': 'Monospace', '拼写检查': 'Spellcheck',
  '源码自动换行': 'Wrap source lines', '源码行号': 'Source line numbers', '缩进宽度': 'Indent size',
  '输入辅助': 'Typing assistance',
  '智能引号、破折号与省略号': 'Smart quotes, dashes and ellipses',
  '自动配对括号与引号': 'Automatically pair brackets and quotes',
  '输入和粘贴网址时创建链接': 'Create links when typing or pasting URLs',
  '智能标点仅用于新键入的正文；代码、公式、Front Matter、HTML、网址及输入法组合保持原样。粘贴和已有文档不会批量转换。': 'Smart punctuation applies only to newly typed prose. Code, formulas, front matter, HTML, URLs and IME composition stay as entered. Pasted text and existing documents are not converted.',
  '代码自动换行': 'Wrap code lines', '代码行号': 'Code line numbers',
  '新代码块默认语言': 'Default language for new code blocks',
  '留空表示纯文本。仅应用于新插入的代码块；已有代码语言保持不变，缩进宽度与源码编辑器一致。': 'Leave blank for plain text. Applies only to newly inserted code blocks. Existing languages stay unchanged; indentation uses the source editor setting.',
  '表格操作': 'Table actions', '第 {row} 行，第 {column} 列': 'Row {row}, column {column}',
  '{rows} 行 × {columns} 列': '{rows} rows × {columns} columns', '已选 {rows} 行、{columns} 列': '{rows} rows and {columns} columns selected',
  '向上插入行': 'Insert row above', '向下插入行': 'Insert row below', '向左插入列': 'Insert column left', '向右插入列': 'Insert column right',
  '删除所选行': 'Delete selected rows', '删除所选列': 'Delete selected columns',
  '列左对齐': 'Align column left', '列居中对齐': 'Align column center', '列右对齐': 'Align column right',
  '删除整张表格': 'Delete table', '表头': 'Header row',
  'Tab 切换单元格，末格新增一行': 'Tab moves between cells and adds a row from the final cell',
  '当前表格包含合并单元格，结构操作暂不可用。': 'This table contains merged cells. Structural actions are unavailable.',
  '选择整行': 'Select row', '选择整列': 'Select column',
  '表格行': 'Rows', '列': 'Columns', '对齐': 'Alignment', '左对齐': 'Left', '居中': 'Center', '右对齐': 'Right',
  '公式源码': 'Formula source', '公式预览': 'Formula preview', '行内公式源码': 'Inline formula source', '编辑公式': 'Edit formula',
  '公式无法渲染；源码已保留，可在下方修复。': 'Unable to render the formula. Its source is preserved and can be corrected below.',
  '代码块附加信息': 'Code block metadata', '例如 title="example.ts" {1,3-5}': 'For example, title="example.ts" {1,3-5}',
  '行内公式': 'Inline math', '插入行': 'Insert row', '插入列': 'Insert column', '行操作': 'Row actions', '列操作': 'Column actions',
  '四级标题': 'Heading 4', '五级标题': 'Heading 5', '六级标题': 'Heading 6', '分隔线': 'Divider', '高级': 'Advanced',
  'Markdown 扩展': 'Markdown extensions',
  '高亮使用 ==文字==；上标使用 ^文字^；下标使用 ~文字~；下划线使用 <u>文字</u>。上标、下标中的空格以反斜杠转义。': 'Use ==text== for highlight, ^text^ for superscript, ~text~ for subscript, and <u>text</u> for underline. Escape spaces in superscript and subscript with a backslash.',
  '关闭后保留原文；代码、公式和链接地址始终按原样处理。Emoji 名称表已随应用离线提供。': 'Disabled extensions keep the original text. Code, formulas and link addresses stay unchanged. The emoji catalog is included for offline use.',
  '高亮': 'Highlight', '上标': 'Superscript', '下标': 'Subscript', '下划线': 'Underline',
  'Emoji 短名称（如 :smile:）': 'Emoji short names (e.g. :smile:)', 'Emoji 自动补全': 'Emoji completion',
  '自动保存已命名文档': 'Autosave named documents', '自动保存间隔（秒）': 'Autosave interval (seconds)',
  '启动时恢复上次文档和文件夹': 'Restore the last documents and folder on startup',
  '恢复草稿始终启用；存在外部修改冲突时自动保存会暂停。': 'Draft recovery is always enabled. Autosave pauses when an external change causes a conflict.',
  '导出时添加目录': 'Include a table of contents', '使用 Front Matter 的标题和作者': 'Use the title and author from front matter',
  'PDF 纸张': 'PDF paper size', '页边距（毫米）': 'Margins (mm)', '横向': 'Landscape', '页码': 'Page numbers', '页眉': 'Header', '页脚': 'Footer',
  '自定义主题 CSS': 'Custom theme CSS', '即时应用于编辑器，也用于带样式的导出。可选择本地 CSS 文件。': 'Applies to the editor immediately and to styled exports. You can choose a local CSS file.',
  '导入 CSS 主题': 'Import CSS theme', '自定义 CSS': 'Custom CSS',
  '你的写作空间': 'Your writing space', '工作区导航': 'Workspace navigation',
  '搜索命令与操作': 'Search commands and actions', '命令面板': 'Command palette', '命令面板…': 'Command palette…', '命令面板（Ctrl+K）': 'Command palette (Ctrl+K)',
  '搜索命令': 'Search commands', '可用命令': 'Available commands',
  '输入操作，例如：导出、专注、保存全部…': 'Search actions, e.g. export, focus, save all…',
  '没有匹配的命令。试试“文件”或“视图”。': 'No matching commands. Try “File” or “View”.',
  '↑ ↓ 选择 · Enter 执行': '↑ ↓ select · Enter run', '项操作 · Esc 关闭': 'actions · Esc close', '{count} 项操作 · Esc 关闭': '{count} actions · Esc close',
  '文档侧栏': 'Document sidebar', '关闭侧栏': 'Close sidebar', '大纲': 'Outline', '文档大纲': 'Document outline',
  '文件侧栏': 'File sidebar', '文件树': 'File tree', '列表': 'List', '刷新': 'Refresh', '管理工作区': 'Manage workspace',
  '筛选文件': 'Filter files', '筛选文件…': 'Filter files…', '切换排序': 'Change sort order',
  '文件数量过多，仅显示前 5,000 项。': 'There are too many files. Showing the first 5,000 entries.',
  '打开一个文件夹以浏览 Markdown 和文本文件。': 'Open a folder to browse Markdown and text files.',
  '显示标题层级': 'Heading depth', '当前文档还没有标题。': 'This document has no headings yet.', '第 {value1} 行': 'Line {value1}',
  '管理 {value1}': 'Manage {value1}', '管理文档': 'Manage document', '操作': 'Action', '文件操作': 'File action',
  '重命名或移动文档': 'Rename or move document', '移入恢复区': 'Move to recovery', '恢复最近移除的文档': 'Restore the last removed document',
  '相对于工作区的路径': 'Path relative to the workspace', '目标路径': 'Target path',
  '文档会移入此工作区的恢复区，之后可从“管理工作区”恢复。图片资源会保留。': 'The document moves to this workspace’s recovery area. Restore it later from “Manage workspace”. Images are kept.',
  '恢复最近移除的文档；同名文档已经存在时不会覆盖。': 'Restores the last removed document. An existing document with the same name will not be overwritten.',
  '取消': 'Cancel', '处理中…': 'Working…', '执行': 'Run',
  '最近项目': 'Recent items', '最近项目…': 'Recent items…', '清除未固定的记录': 'Clear unpinned items', '还没有最近项目。': 'No recent items yet.',
  '固定': 'Pin', '取消固定': 'Unpin', '{action} {path}': '{action} {path}', '{value1} {value2}': '{value1} {value2}',
  '快速打开': 'Quick open', '快速打开…': 'Quick open…', '快速打开文件': 'Quick open file', '输入文件名': 'Enter filename',
  '按名称快速打开文件…': 'Quickly open a file by name…', '工作区搜索': 'Workspace search', '输入搜索内容': 'Enter search text',
  '在文件夹中搜索…': 'Search in folder…', '搜索文件夹': 'Search folder', '搜索文件夹内容': 'Search folder contents', '搜索文件夹（Ctrl+Shift+F）': 'Search folder (Ctrl+Shift+F)',
  '在文件夹中查找…': 'Find in folder…', '请先打开一个文件夹。': 'Open a folder first.', '没有匹配的文件。': 'No matching files.',
  '正在搜索…': 'Searching…', '输入内容以搜索当前文件夹中的 Markdown 和文本文件。': 'Search the Markdown and text files in the current folder.',
  '（空行）': '(empty line)', '没有搜索结果。': 'No search results.', '（结果已截断）': '(results truncated)',
  '已扫描 {files} 个文件，找到 {count} 处': 'Scanned {files} files, found {count} matches',
  '已扫描': 'Scanned', '个文件，找到': 'files, found', '处': 'matches', '第': 'Line', '行': '',
  '查找': 'Find', '查找…': 'Find…', '查找文档': 'Find in document', '查找与替换': 'Find and replace', '替换': 'Replace', '替换…': 'Replace…', '替换为': 'Replace with', '全部替换': 'Replace all',
  '输入查找内容': 'Enter search text', '表达式无效': 'Invalid expression', '无结果': 'No results', '区分大小写': 'Match case', '全词匹配': 'Whole word', '正则表达式': 'Regular expression',
  '上一个（Shift+Enter）': 'Previous (Shift+Enter)', '下一个（Enter）': 'Next (Enter)', '关闭查找': 'Close find',
  '粗体': 'Bold', '斜体': 'Italic', '删除线': 'Strikethrough', '行内代码': 'Inline code', '一级标题': 'Heading 1', '二级标题': 'Heading 2', '三级标题': 'Heading 3',
  '正文': 'Paragraph', '引用': 'Blockquote', '无序列表': 'Bullet list', '有序列表': 'Numbered list', '任务列表': 'Task list',
  '代码块': 'Code block', '表格': 'Table', '链接': 'Link', '目录': 'Table of contents', '脚注': 'Footnote', '提示块': 'Callout', '公式': 'Math', '文字': 'Text',
  '粗体（Ctrl+B）': 'Bold (Ctrl+B)', '斜体（Ctrl+I）': 'Italic (Ctrl+I)', '插入格式': 'Insert formatting',
  '图片': 'Image', '插入图片': 'Insert image', '插入图片…': 'Insert image…', '插入本地图片': 'Insert local image', '管理文档图片': 'Manage document images', '管理文档图片…': 'Manage document images…',
  '插入音视频…': 'Insert audio / video…', '上传文档图片…': 'Upload document images…', '插入本地音视频': 'Insert local audio / video', '音视频': 'Audio / video',
  '选择图片上传程序': 'Choose image upload program', '可执行程序': 'Executable program',
  '编辑视图': 'Editing view', '所见即所得': 'Visual editor', '所见即所得模式': 'Visual editing mode',
  'Markdown 源码': 'Markdown source', 'Markdown 源码模式': 'Markdown source mode', '源码': 'Source', '源码模式': 'Source mode', '切换源码模式': 'Toggle source mode',
  '并排': 'Split', '并排预览': 'Split preview', '源码与预览并排': 'Source and preview side by side', '可编辑': 'Editable',
  '显示文档大纲': 'Show document outline', '显示文件侧栏': 'Show file sidebar', '切换侧栏': 'Toggle sidebar',
  '专注': 'Focus', '专注模式': 'Focus mode', '专注模式（F8）': 'Focus mode (F8)', '切换专注模式': 'Toggle focus mode',
  '打字机': 'Typewriter', '打字机模式': 'Typewriter mode', '打字机模式（F9）': 'Typewriter mode (F9)', '切换打字机模式': 'Toggle typewriter mode',
  '重新加载': 'Reload', '开发者工具': 'Developer tools', '实际大小': 'Actual size', '放大': 'Zoom in', '缩小': 'Zoom out', '全屏': 'Full screen',
  '实时预览': 'Live preview', 'Markdown 实时预览': 'Live Markdown preview', '更新中…': 'Updating…', '已同步': 'Synced', '预览失败：': 'Preview failed: ', '预览失败：{error}': 'Preview failed: {error}',
  '字数统计': 'Writing statistics', '词数': 'Words', '字符（含空格）': 'Characters (with spaces)', '字符（不含空格）': 'Characters (without spaces)',
  '段落': 'Paragraphs', '行数': 'Lines', '预计阅读': 'Reading time', '分钟': 'minutes', '{count} 分钟': '{count} minutes',
  '选中内容': 'Selected text', '当前文档': 'Current document', '关闭字数统计': 'Close writing statistics', '查看整个文档': 'View whole document',
  '查看字数、段落和阅读时间': 'View word count, paragraphs and reading time', '词 ·': 'words ·', '字符': 'characters', '{words} 词 · {characters} 字符': '{words} words · {characters} characters',
  '写作目标': 'Writing goal', '写作目标…': 'Writing goal…', '设定写作目标': 'Set writing goal', '设定目标': 'Set goal',
  '开始': 'Start', '本篇目标已完成。继续记录你的想法。': 'You’ve reached your goal. Keep writing your ideas.',
  '距离目标还有 {value1} 字符': '{value1} characters to go', '给这一篇文章设定一个可实现的目标。': 'Set an achievable goal for this document.',
  '本篇文档目标（正文字符，不含空白）': 'Document goal (characters, excluding whitespace)', '目标字数': 'Target character count', '{count} 字符': '{count} characters', '清除目标': 'Clear goal', '保存目标': 'Save goal',
  '准备就绪': 'Ready', '正在编辑': 'Editing', '正在准备编辑器…': 'Preparing editor…', '正在保存…': 'Saving…',
  '未保存文档': 'Unsaved document', '尚未保存': 'Not saved yet', '未保存': 'Unsaved', '已保存': 'Saved', '新文档': 'New document',
  '文档没有需要保存的修改': 'No document changes to save', '所有文档已保存': 'All documents saved', '已保存：{value1}': 'Saved: {value1}',
  '检测到文件冲突': 'File conflict detected', '保存失败': 'Save failed', '保存失败：{value1}': 'Save failed: {value1}', '另存为失败：{value1}': 'Save as failed: {value1}',
  '插入本地图片前需要先保存文档': 'Save the document before inserting a local image', '已取消保存，未插入图片。': 'Save cancelled. No image was inserted.',
  '已复制图片：{value1}': 'Image copied: {value1}', '保存图片失败：{value1}': 'Failed to save image: {value1}', '已插入图片：{value1}': 'Image inserted: {value1}', '插入图片失败：{value1}': 'Failed to insert image: {value1}',
  '正在生成 {value1}…': 'Generating {value1}…', '已取消导出': 'Export cancelled', '已导出：{value1}': 'Exported: {value1}', '导出失败': 'Export failed', '导出失败：{value1}': 'Export failed: {value1}',
  '已打开：{value1}': 'Opened: {value1}', '已打开文件夹：{value1}': 'Folder opened: {value1}', '工作区已更新': 'Workspace updated',
  '打开文件失败：{value1}': 'Failed to open file: {value1}', '打开文件夹失败：{value1}': 'Failed to open folder: {value1}', '刷新文件夹失败：{value1}': 'Failed to refresh folder: {value1}',
  '打开工作区文件失败：{value1}': 'Failed to open workspace file: {value1}', '打开启动文件失败：{value1}': 'Failed to open launch file: {value1}', '打开最近项目失败：{value1}': 'Failed to open recent item: {value1}',
  '已复制文档': 'Document copied', '复制失败：{value1}': 'Copy failed: {value1}', '已取消操作。': 'Operation cancelled.',
  '请先保存文档，再打开链接。': 'Save the document before opening this link.', '打开链接失败：{value1}': 'Failed to open link: {value1}',
  '搜索失败：{value1}': 'Search failed: {value1}', '检测到外部文件变化': 'External file change detected', '已重新加载外部修改': 'External changes reloaded',
  '没有可撤销的修改': 'Nothing to undo', '没有可重做的修改': 'Nothing to redo', '已撤销': 'Undone', '已重做': 'Redone',
  '编辑器初始化失败：{value1}': 'Failed to initialize editor: {value1}', '源码编辑器初始化失败：{value1}': 'Failed to initialize source editor: {value1}',
  '恢复上次项目失败：{value1}': 'Failed to restore the last session: {value1}', '无法读取恢复草稿：{value1}': 'Failed to read recovery drafts: {value1}',
  '恢复草稿写入失败：{value1}': 'Failed to write recovery draft: {value1}', '草稿保存失败：{value1}': 'Failed to save draft: {value1}', '退出前保存草稿失败：{value1}': 'Failed to save draft before closing: {value1}',
  '发现恢复草稿': 'Recovery drafts found', '查看恢复草稿': 'View recovery drafts', '这些内容来自上次未完成的编辑。草稿不会自动覆盖原文件。': 'These drafts come from unfinished edits. They will not overwrite the original files automatically.',
  '恢复': 'Restore', '丢弃': 'Discard', '恢复草稿已不存在。': 'The recovery draft no longer exists.', '已恢复草稿，尚未写入原文件': 'Draft restored; the original file has not been updated',
  '恢复草稿失败：{value1}': 'Failed to restore draft: {value1}', '恢复草稿已另存为：{value1}': 'Recovery draft saved as: {value1}',
  '文件发生外部变化': 'File changed externally', '文件冲突': 'File conflict', '磁盘上的原文件已被删除。': 'The original file has been deleted from disk.', '磁盘上的文件已被其他程序修改。': 'Another program has changed the file on disk.',
  '为避免覆盖其他修改，请选择处理方式。': 'Choose how to handle these changes before overwriting them.', '放弃本地修改并重新加载': 'Discard local changes and reload', '覆盖外部版本': 'Overwrite external version', '已放弃本地修改并重新加载': 'Local changes discarded and file reloaded',
  '文档尚未保存': 'Document not saved', '未保存的修改': 'Unsaved changes', '{name} 有未保存的修改。': '{name} has unsaved changes.', '{count} 个文档有未保存的修改。': '{count} documents have unsaved changes.',
  '你可以保存、保留恢复草稿后退出，或者放弃修改。': 'Save your documents, keep recovery drafts and quit, or discard changes.', '选择如何处理这些修改。': 'Choose how to handle these changes.', '继续前请选择如何处理。': 'Choose how to handle the changes before continuing.',
  '放弃修改': 'Discard changes', '保留草稿并退出': 'Keep drafts and quit', '放弃并退出': 'Discard and quit',
  '文档转换': 'Document conversion', '把创作带到更多地方': 'Take your writing further',
  '将「': 'Convert “', '」转换为 Word、电子书或排版源码，也可导入已有文档。': '” to Word, an ebook or typesetting source, or import an existing document.',
  '将「{name}」转换为 Word、电子书或排版源码，也可导入已有文档。': 'Convert “{name}” to Word, an ebook or typesetting source, or import an existing document.',
  '正在检查转换引擎…': 'Checking conversion engine…', '转换引擎尚未就绪': 'Conversion engine not ready', '随应用提供 · 可离线使用': 'Included with the app · Works offline',
  '使用选定程序': 'Using the selected program', '使用系统程序': 'Using the system program', '重新检测': 'Check again',
  '输出格式': 'Output format', 'Word 文档': 'Word document', '标题、表格、脚注与图片': 'Headings, tables, footnotes and images',
  '开放文档格式': 'Open document format', 'EPUB 电子书': 'EPUB ebook', '目录与章节导航': 'Table of contents and chapter navigation',
  'RTF 文档': 'RTF document', '通用文字处理格式': 'General word processing format', 'LaTeX 源码': 'LaTeX source', '排版与公式源码': 'Typesetting and math source',
  'HTML 文档': 'HTML document', '独立网页文档': 'Standalone web document', '技术文档与 Sphinx': 'Technical documents and Sphinx',
  'Org 文档': 'Org document', '结构化笔记': 'Structured notes', '正文与基础结构': 'Text and basic structure', '转换 Markdown 方言': 'Convert Markdown dialects',
  '生成目录': 'Generate table of contents', '章节编号': 'Number sections', '完整独立文档': 'Standalone document', '使用 Word 参考样式': 'Use Word reference styles', '选择参考文档': 'Choose reference document',
  '导入已有文档': 'Import an existing document', '选择 Word、ODT、EPUB、HTML、LaTeX 等文件，另存为 Markdown，保留原文件和提取图片。': 'Choose a Word, ODT, EPUB, HTML, LaTeX or other document. Save it as Markdown while preserving the original and extracting images.',
  '选择并导入…': 'Choose and import…', '高级设置': 'Advanced settings', '附加转换选项（每行一个）': 'Additional conversion options (one per line)', '附加转换选项': 'Additional conversion options',
  '支持目录深度、标题层级、换行与代码配色；输入输出路径由文件选择框指定。': 'Supports table of contents depth, heading levels, wrapping and code colors. Choose input and output paths using the file dialogs.',
  '转换超时（秒）': 'Conversion timeout (seconds)', '转换超时': 'Conversion timeout', '选择 Pandoc 程序': 'Choose Pandoc program', 'Pandoc 可执行程序': 'Pandoc executable', '恢复自动检测': 'Restore automatic detection',
  '选择输出位置…': 'Choose output location…', '选择导入文档…': 'Choose document to import…', '已取消': 'Cancelled', '已导出：': 'Exported: ', '已导入：': 'Imported: ', '已导入：{path}': 'Imported: {path}',
  '正在取消转换…': 'Cancelling conversion…', '取消转换': 'Cancel conversion', '转换提示': 'Conversion notes',
  '选择 Word 参考样式文档': 'Choose Word reference document', '选择要转换的文档': 'Choose document to convert', '支持的文档': 'Supported documents', '将导入内容保存为 Markdown': 'Save imported contents as Markdown',
  '主题库': 'Theme library', '主题库…': 'Theme library…', '主题工坊': 'Theme studio', '切换主题': 'Change appearance', '切换明亮 / 暗色主题': 'Switch light / dark appearance',
  '跟随系统': 'Follow system', '明亮': 'Light', '暗色': 'Dark', '浅色': 'Light', '深色': 'Dark',
  '澄蓝': 'Clear Blue', '暖纸': 'Warm Paper', '苔庭': 'Moss Garden', '雾玫': 'Misty Rose', '深空': 'Deep Space', '石墨': 'Graphite', '夜林': 'Night Forest', '暮紫': 'Purple Dusk',
  '清晰留白与柔和蓝色，适合每天的创作。': 'Clean space and soft blue for everyday writing.',
  '奶油色纸面与棕色墨迹，让长文更舒展。': 'Cream paper and warm brown ink for comfortable long reads.',
  '轻盈的绿意、安静的白，给思考留一处花园。': 'Gentle green and quiet white make room for thought.',
  '克制的玫瑰色细节，适合随笔与阅读。': 'Subtle rose details for notes and reading.',
  '深蓝底色与淡紫高光，照亮夜里的灵感。': 'Deep blue and pale violet brighten nighttime ideas.',
  '低彩度的石墨与银灰，让文字成为主角。': 'Muted graphite and silver keep your words in focus.',
  '深绿色纸面与薄荷色标记，平静而有层次。': 'Deep green and mint accents create quiet depth.',
  '暗梅色与柔和桃色，为夜读添一点温度。': 'Dark plum and soft peach bring warmth to night reading.',
  '为每次创作，选择一种氛围。': 'Find an atmosphere for every story.',
  '浅色和深色分别记住你的选择。内置主题原创设计，也可导入熟悉的 Markdown CSS。': 'Light and dark modes remember separate themes. Choose an original built-in theme or import your own Markdown CSS.',
  '款主题': 'themes', '个自定义主题 · 保存在本机': 'custom themes · Stored locally', '{count} / {limit} 个自定义主题 · 保存在本机': '{count} / {limit} custom themes · Stored locally',
  '主题明暗分类': 'Theme appearance', '搜索主题': 'Search themes', '搜索名称或风格': 'Search name or style', '导入 CSS 主题文件': 'Import CSS theme file', '导入 CSS': 'Import CSS', '导出 CSS': 'Export CSS',
  '全部': 'All', '内置': 'Built-in', '我的主题': 'My themes', '新建主题': 'New theme', '自定义': 'Custom', '已选': 'Selected',
  '原创内置主题': 'Original built-in theme', '我的自定义主题': 'My custom theme', '用自己的色彩与字体，定制独特的写作环境。': 'Create your own writing space with custom colors and fonts.',
  '{value1}主题列表': '{value1} theme list', '预览主题 {value1}': 'Preview theme {value1}', '{value1}主题缩略预览': 'Theme thumbnail: {value1}', '{value1}主题详细预览': 'Theme preview: {value1}',
  '当前{value1}主题': 'Current {value1} theme', '设为{value1}主题': 'Use as {value1} theme', '已应用「{value1}」。': 'Applied “{value1}”.', '已设为{value1}主题，切换到{value2}模式时生效。': 'Saved as your {value1} theme. It will appear in {value2} mode.',
  '查看 CSS': 'View CSS', '编辑 / 重命名': 'Edit / rename', '删除': 'Delete', '保留': 'Keep', '确认删除': 'Confirm deletion',
  '删除「': 'Delete “', '」？当前选中的主题会恢复为默认主题。': '”? If selected, the default theme will be restored.', '删除「{name}」？当前选中的主题会恢复为默认主题。': 'Delete “{name}”? If selected, the default theme will be restored.',
  '没有匹配的主题。试试其他分类，或导入自己的 CSS。': 'No matching themes. Try another category or import your CSS.',
  '查看内置主题': 'View built-in theme', '编辑主题': 'Edit theme', '查看「{value1}」': 'View “{value1}”', '编辑自定义主题': 'Edit custom theme', '关闭主题编辑': 'Close theme editor',
  '主题名称': 'Theme name', '适用模式': 'Appearance', '主题适用模式': 'Theme appearance', '简介': 'Description', '主题简介': 'Theme description', '主题 CSS': 'Theme CSS',
  '支持 #write、.milkdown、.ProseMirror 选择器。外部资源会自动过滤，内嵌图片和字体可保留。原偏好设置中的自定义 CSS 继续作为最后一层叠加。': 'Supports #write, .milkdown and .ProseMirror selectors. External resources are filtered; embedded images and fonts are kept. Custom CSS from Preferences is applied last.',
  '主题编辑实时预览': 'Live theme editor preview', '返回主题库': 'Back to theme library', '取消编辑': 'Cancel editing', '复制后编辑': 'Copy and edit', '保存主题': 'Save theme',
  '已复制「{value1}」，可自由修改。': 'Copied “{value1}”. You can edit it freely.', '主题已保存。': 'Theme saved.', '主题已保存；已移除 {value1} 处外部资源引用。': 'Theme saved; removed {value1} external resource references.',
  '已导入；已移除 {value1} 处外部资源引用。保存后即可应用。': 'Imported; removed {value1} external resource references. Save the theme to apply it.', '已导入主题，可调整名称和明暗归属。': 'Theme imported. You can edit its name and appearance.', '主题已删除。': 'Theme deleted.',
  '主题已应用，但本地存储空间不足，重启后可能无法保留。请导出重要主题。': 'Theme applied, but local storage is full and it may not persist after restarting. Export any themes you want to keep.',
  '请选择 .css 主题文件。': 'Choose a .css theme file.', '主题 CSS 不能超过 100 KB。': 'Theme CSS must be 100 KB or smaller.', '主题名称需为 1–56 个字符。': 'Theme names must contain 1–56 characters.',
  '所选主题与明暗模式不匹配。': 'The selected theme does not match this appearance.', '主题库最多保存 40 个自定义主题。': 'The theme library can store up to 40 custom themes.', '主题标识无效或重复。': 'Theme ID is invalid or duplicated.', '主题明暗模式无效。': 'Invalid theme appearance.',
  '内置主题不能编辑，请先复制。': 'Copy a built-in theme before editing it.', '找不到主题。': 'Theme not found.', '内置主题不能删除。': 'Built-in themes cannot be deleted.',
  '给文字一处风景': 'A place for your words', '让灵感落在纸上，保持专注，写下你的故事。': 'Put inspiration on the page. Stay focused and tell your story.', '好文字，也值得被好好看见。': 'Good words deserve a thoughtful setting.',
  '今日灵感': 'Today’s inspiration', '一份清晰的创作空间': 'A clear space to create', '正文、': 'Text, ', '强调': 'emphasis', '、': ', ', '想法': 'ideas', '与': ' and ', '参考链接': 'references', '，在恰好的层次中相遇。': ' meet in a balanced layout.',
  '开始写作': 'Start writing', '章节': 'Chapter', '进度': 'Progress', '新的故事': 'A new story', '正在发生': 'In progress', 'CSS 超过 100 KB，缩小后可预览。': 'CSS exceeds 100 KB. Reduce its size to preview it.',
  'assets resources 图片资源': 'assets resources images', 'pandoc word docx epub latex odt 转换 导入': 'pandoc word docx epub latex odt convert import', 'themes CSS 外观': 'themes CSS appearance',
  '应用没有写入该路径的授权，请使用“另存为”。': 'The app is not authorized to write to this path. Use “Save as”.', '命令行仅支持 Markdown、文本文件和文件夹。': 'Command-line input supports only Markdown files, text files and folders.',
  '参考样式须为 DOCX 文件。': 'The reference document must be a DOCX file.', '目标是已打开的文档，请选择其他输出路径。': 'The target is an open document. Choose another output path.',
  '转换文档路径未获授权。': 'The conversion document path is not authorized.', '导入内容请保存为 .md 或 .markdown 文件。': 'Save imported contents as a .md or .markdown file.',
  '图片管理文档路径未获授权。': 'The image management document path is not authorized.', '文档路径未获授权。': 'The document path is not authorized.', '此项目不在最近项目中。': 'This item is not in the recent list.',
  '请先打开文件夹。': 'Open a folder first.', '尚未打开工作区。': 'No workspace is open.', '当前文档路径未获授权，请先保存文档。': 'This document path is not authorized. Save the document first.',
  '当前文档路径未获授权。': 'This document path is not authorized.', '图片地址无效。': 'Invalid image address.', '目标文件已在另一个标签中打开，请选择其他文件名。': 'The target file is open in another tab. Choose another filename.',
  '无效的草稿 ID。': 'Invalid draft ID.', '无效的文档会话。': 'Invalid document session.', '无权读取预览资源。': 'Preview resources are not authorized.',
  '文档已关闭，请重新打开图片管理。': 'The document is closed. Reopen image management.', '文档在操作期间发生变化，资源副本已保留；请刷新后重试。': 'The document changed during the operation. Resource copies were kept; refresh and try again.',
  '图片资源管理': 'Image resource manager', '引用修改支持文档撤销 · 原文件保留 · 恢复区可还原': 'Reference edits support undo · Original files are kept · Recovery is available',
  '整理图片引用、收纳本地资源，找回缺失的文件。': 'Organize image references, collect local resources and find missing files.',
  '刷新检查': 'Refresh and check', '图片资源分类': 'Image resource categories', '文档引用': 'Document references', '未使用资源': 'Unused resources', '恢复区': 'Recovery',
  '筛选图片资源': 'Filter image resources', '搜索文件名或图片 URL': 'Search filename or image URL',
  '本地图片': 'Local image', '远程图片': 'Remote image', '内嵌图片': 'Embedded image', '文件缺失': 'Missing file', '不可访问': 'Unavailable', '大小未知': 'Unknown size',
  '无法预览此图片': 'Cannot preview this image', '暂无本地预览': 'No local preview', '没有匹配的图片。': 'No matching images.', '当前文档没有图片引用。': 'This document has no image references.', '正在检查文档图片…': 'Checking document images…',
  '处引用 ·': 'references ·', '处引用': 'references', '{count} 处引用': '{count} references', '已收纳': 'Collected',
  '已在文档资源目录': 'Already in document assets', '复制到文档资源目录': 'Copy to document assets', '图片文件名': 'Image filename', '重命名引用': 'Rename references',
  '生成新文件并更新全部图片引用。保留原文件，保证撤销后图片仍可使用。': 'Creates a new file and updates all image references. The original remains available when you undo.',
  '移除全部图片引用': 'Remove all image references', '保留图片说明文字与资源文件，可通过文档撤销恢复引用。': 'Keeps image descriptions and resource files. Undo in the document to restore references.',
  '选择一张图片，查看引用并整理资源。': 'Select an image to inspect references and organize its resources.',
  '检查范围：已授权目录中的': 'Checked scope: ', '份文档及打开标签的未保存内容。仅列出当前文档资源目录中的图片。': 'documents in authorized folders and unsaved content in open tabs. Only images in the current document’s assets are listed.',
  '检查范围：已授权目录中的 {count} 份文档及打开标签的未保存内容。仅列出当前文档资源目录中的图片。': 'Checked {count} documents in authorized folders and unsaved content in open tabs. Only images in the current document’s assets are listed.',
  '没有匹配的资源。': 'No matching resources.', '未发现可整理的孤立图片。': 'No unused images found.', '移入前再次检查所有引用和文件版本。引用检查不完整时禁止移动。': 'References and file versions are checked again before moving. Moving is disabled if reference checks are incomplete.',
  '图片保存在本地恢复区。恢复到原目录；若同名文件已存在，保留两份并停止覆盖。': 'Images are stored in local recovery and restored to their original folder. If a file with the same name exists, both copies are kept without overwriting.',
  '没有匹配的恢复记录。': 'No matching recovery records.', '恢复区为空。': 'Recovery is empty.', '恢复图片': 'Restore image', '无法读取图片资源。': 'Cannot read image resources.', '图片操作未完成。': 'The image operation did not finish.',
  '图片总量超过转换输入上限': 'Total image size exceeds the conversion input limit', '图片超过 25 MB': 'Image exceeds 25 MB', '未能嵌入图片：': 'Could not embed image: ', '此转换格式未嵌入图片：': 'Images were not embedded in this format: ',
  '危险的 Markdown 链接或图片地址已移除，显示文字已保留。': 'Unsafe Markdown links and image addresses were removed; visible text was preserved.',
  '原始 HTML 已按安全规则整理，脚本、事件属性与危险协议不会进入导出。': 'Raw HTML was sanitized. Scripts, event attributes and unsafe protocols are excluded from the export.',
  '元数据字段 {value1} 中的原始引擎指令已清空；其他标题、作者与正文均保留。': 'Raw engine instructions in metadata field {value1} were cleared. Other titles, authors and document text were kept.',
  '元数据字段 {value1} 已按安全规则整理，显示文字与安全格式保留。': 'Metadata field {value1} was sanitized; visible text and safe formatting were kept.',
  '元数据字段 {value1} 引用的原始引擎指令已清空；其他字段与正文均保留。': 'Raw engine instructions referenced by metadata field {value1} were cleared. Other fields and document text were kept.',
  '文档中的 YAML 元数据格式有误，已停止转换；原文档未修改。': 'YAML metadata is invalid. Conversion was stopped and the original document was not changed.', '无法安全定位 YAML 元数据边界，已停止转换。': 'Cannot safely locate the YAML metadata boundary. Conversion was stopped.',
  '保存文件时发生未知错误。': 'An unknown error occurred while saving.', '保存过程中检测到新的外部修改。': 'A new external change was detected while saving.', '文件已被其他程序修改或删除。': 'Another program changed or deleted the file.', '文件路径包含非法空字符。': 'The file path contains a null character.',
  '文件不在当前工作区内或类型不受支持。': 'The file is outside this workspace or its type is unsupported.', '文件扩展名必须为 .md、.markdown 或 .txt。': 'The file extension must be .md, .markdown or .txt.', '请输入工作区内有效的相对路径。': 'Enter a valid relative path inside the workspace.',
  '目标目录超出工作区。': 'The target folder is outside the workspace.', '目标不是普通文件。': 'The target is not a regular file.', '没有可恢复的文档。': 'No document is available for recovery.',
  '文档含 HTML 资源链接，请在原目录重命名，或先将 HTML 链接改为 Markdown 链接。': 'The document contains HTML resource links. Rename it in its original folder, or convert the links to Markdown first.', '文档含工作区外部的相对链接，无法自动移动。': 'The document has relative links outside the workspace and cannot be moved automatically.',
  '移动期间原文件发生变化，已保留原文件和目标副本。': 'The original file changed while moving. Both the original and target copy were kept.',
  '不支持的导出格式。': 'Unsupported export format.', '导出不能覆盖当前 Markdown 原文件。': 'Export cannot overwrite the original Markdown file.', '输出目标不是可覆盖的普通文件。': 'The output target is not a regular file that can be overwritten.', '文档过长，图片导出最多支持 16,000 像素高度，请使用 PDF 导出。': 'This document exceeds the 16,000-pixel image export height limit. Export as PDF instead.', '无法捕获文档图片。': 'Cannot capture the document image.',
  '不支持的转换参数：{value1}。可用目录深度、换行、标题、代码配色等选项；文件路径请使用专用选择入口。': 'Unsupported conversion argument: {value1}. Use options for contents depth, wrapping, headings or code colors. Choose file paths using the dedicated dialogs.',
  '尚未找到 Pandoc。请选择程序文件，或将 Pandoc 加入系统 PATH。': 'Pandoc was not found. Choose its executable, or add Pandoc to your system PATH.', '可以离线转换文档': 'Document conversion is available offline', '当前窗口已有转换正在进行。': 'A conversion is already running in this window.',
  '该程序没有返回 Pandoc 版本。': 'The program did not return a Pandoc version.', '请先选择 Word 参考样式文档。': 'Choose a Word reference document first.', '该文件格式暂不支持导入。': 'Import is not supported for this file format.',
  '导入须保存为独立 Markdown 文档。': 'Save the import as a separate Markdown document.', '导入文件须为普通文件，大小不超过 100 MB。': 'The import must be a regular file no larger than 100 MB.', '转换后的 Markdown 超过 20 MB。': 'Converted Markdown exceeds 20 MB.',
  '转换输出不能覆盖符号链接。': 'Conversion output cannot overwrite a symbolic link.', '转换期间输出文件发生外部修改，已保留外部版本。': 'The output file changed externally during conversion. The external version was kept.', '转换期间目标 Markdown 发生外部修改，已保留外部版本。': 'The target Markdown file changed externally during conversion. The external version was kept.', '目标 Markdown 发生外部修改。': 'The target Markdown file changed externally.',
  '转换结果为空，未覆盖目标文件。': 'The conversion result is empty. The target file was not overwritten.', '转换结果超过 100 MB，未覆盖目标文件。': 'The conversion result exceeds 100 MB. The target file was not overwritten.',
  '转换已取消。': 'Conversion cancelled.', '转换超时，原文件和现有导出文件均已保留。': 'Conversion timed out. The original and existing export files were kept.', '转换诊断过多，已停止。': 'Conversion diagnostics exceeded the limit. Conversion was stopped.', '转换输出过多，已停止。': 'Conversion output exceeded the limit. Conversion was stopped.',
  '无法运行 Pandoc：{value1}': 'Cannot run Pandoc: {value1}', 'Pandoc 转换失败（{value1}）：{value2}': 'Pandoc conversion failed ({value1}): {value2}', '进程终止': 'process terminated', '没有错误详情': 'no error details',
  '转换资源包含不支持的文件类型。': 'Conversion resources contain an unsupported file type.', '资源提取失败，已有文档保持不变：{value1}': 'Resource extraction failed. Existing documents are unchanged: {value1}', ' 提取的资源已保留于 ': ' Extracted resources were kept at ',
  '正在准备文档与图片…': 'Preparing document and images…', '正在读取原文档…': 'Reading source document…', '正在转换为 ': 'Converting to ', '正在转换为 {format}…': 'Converting to {format}…', '正在转换为 Markdown…': 'Converting to Markdown…', '正在安全写入输出文件…': 'Writing output file safely…', '正在保存 Markdown 与图片资源…': 'Saving Markdown and image resources…',
  '文档不在已授权目录内。': 'The document is outside the authorized folders.', '图片文件不存在。': 'Image file does not exist.', '图片不可读取。': 'The image cannot be read.', '图片为空或超过 25 MB。': 'The image is empty or exceeds 25 MB.', '图片不是普通文件。': 'The image is not a regular file.', '图片不是授权目录内的普通文件。': 'The image is not a regular file inside an authorized folder.',
  '图片路径无效。': 'Invalid image path.', '图片路径或编码无效。': 'Invalid image path or encoding.', '图片路径编码无效。': 'Invalid image path encoding.', '图片 URL 协议不受支持。': 'Unsupported image URL protocol.', '图片文件类型不受支持。': 'Unsupported image file type.', '文件内容不是受支持的图片。': 'The file contents are not a supported image.', '不支持该图片格式。': 'Unsupported image format.',
  '图片不在当前文档目录内。': 'The image is outside this document’s folder.', '图片超出已授权目录。': 'The image is outside the authorized folders.', '图片路径含符号链接。': 'The image path contains a symbolic link.', '图片路径含符号链接，已拒绝操作。': 'The image path contains a symbolic link. The operation was rejected.', '目标图片目录含符号链接。': 'The target image folder contains a symbolic link.', '目标图片超出已授权目录。': 'The target image is outside the authorized folders.',
  '图片资源目录超出文档目录。': 'The image assets folder is outside the document’s folder.', '图片资源目录含符号链接或越界。': 'The image assets folder contains a symbolic link or is outside the allowed folder.', '资源目录无效，已停用孤立资源操作。': 'The assets folder is invalid. Unused resource operations are disabled.', '部分图片资源不可读取。': 'Some image resources could not be read.',
  '引用检查不完整（读取失败、符号链接或超出扫描上限），已禁止移入恢复区。': 'Reference checks are incomplete due to unreadable files, symbolic links or scan limits. Moving to recovery is disabled.', '引用检查不完整，不能移动可能仍被使用的图片。': 'Reference checks are incomplete. Images that may still be used cannot be moved.',
  '图片引用已改变，请刷新后重试。': 'Image references changed. Refresh and try again.', '图片引用已改变：{value1}，请重新检查。': 'Image references changed: {value1}. Check again.', '图片已被其他程序修改，请刷新图片管理后重试。': 'Another program changed the image. Refresh image management and try again.', '图片已被其他程序修改，请刷新资源列表后重试。': 'Another program changed the image. Refresh the resource list and try again.',
  '检查期间图片发生变化，请刷新后重试。': 'The image changed while checking. Refresh and try again.', '读取期间图片发生变化。': 'The image changed while reading.', '复制期间图片发生变化，已取消操作。': 'The image changed while copying. The operation was cancelled.', '图片超过 25 MB，无法复制。': 'The image exceeds 25 MB and cannot be copied.', '图片须为非空普通文件，大小不超过 25 MB。': 'The image must be a nonempty regular file no larger than 25 MB.',
  '只能复制或重命名已授权的本地图片。': 'Only authorized local images can be copied or renamed.', '请输入有效的图片文件名，不能包含路径。': 'Enter a valid image filename without a path.', '新文件名与当前文件名相同。': 'The new filename is the same as the current name.', '重命名不能改变图片扩展名。': 'Renaming cannot change the image extension.', '无法为图片分配可用文件名。': 'Cannot assign an available filename to the image.', '无法分配图片文件名。': 'Cannot assign an image filename.',
  '图片已在当前文档资源目录内。': 'The image is already in this document’s assets folder.', '已复制到文档资源目录并更新全部图片引用，原文件保留。': 'Copied to document assets and updated all image references. The original file was kept.', '已将引用更新为 {value1}。原文件保留，文档撤销后仍可使用。{value2}': 'References updated to {value1}. The original file remains available when you undo.{value2}', '保存文档并确认无引用后，可将原件移入恢复区。': 'After saving the document and confirming no references remain, you can move the original to recovery.',
  '已移除 {value1} 处图片引用并保留说明文字，资源文件未删除。': 'Removed {value1} image references and kept their descriptions. Resource files were not deleted.', '图片仍被文档引用，或不在当前文档的资源目录。': 'The image is still referenced or is outside this document’s assets folder.', '移动期间出现新的文档引用或引用检查不完整，已保留原图片。': 'New references appeared during the move or reference checks were incomplete. The original image was kept.',
  '已将 {value1} 移入恢复区，可随时恢复。': 'Moved {value1} to recovery. You can restore it at any time.', '已恢复 {value1}，文档引用未改变。': 'Restored {value1}. Document references were not changed.', '恢复记录不存在，请刷新后重试。': 'The recovery record no longer exists. Refresh and try again.', '恢复文件已被外部修改，原记录已保留。': 'The recovery file changed externally. The original record was kept.', '恢复校验失败，恢复区原件已保留。': 'Recovery verification failed. The original recovery file was kept.',
  '恢复目录无效。': 'Invalid recovery folder.', '图片恢复目录无效。': 'Invalid image recovery folder.', '恢复文件无效。': 'Invalid recovery file.', '恢复记录无效。': 'Invalid recovery record.', '恢复路径含符号链接。': 'The recovery path contains a symbolic link.', '恢复路径无效。': 'Invalid recovery path.', '恢复路径超出资源目录。': 'The recovery path is outside the assets folder.',
  '视频': 'Video', '音频': 'Audio', '视频封面': 'Video poster', '打开远程媒体': 'Open remote media', '（在原文档中播放）': '(play in the original document)', '（源媒体需单独提供）': '(provide the source media separately)',
  '不支持该音视频格式。': 'Unsupported audio or video format.', '不支持该媒体协议。': 'Unsupported media protocol.', '不支持或过大的媒体数据。': 'Media data is unsupported or too large.', '文档尚未保存，不能解析本地媒体。': 'Save the document before resolving local media.', '文档尚未保存，不能解析本地封面。': 'Save the document before resolving a local poster.',
  '媒体路径无效。': 'Invalid media path.', '媒体路径编码无效。': 'Invalid media path encoding.', '媒体不在已授权的文档目录或工作区内。': 'The media is outside the authorized document folder or workspace.', '媒体资源目录超出文档目录。': 'The media assets folder is outside the document’s folder.', '媒体须为普通文件，大小在 1 字节至 100 MB 之间。': 'Media must be a regular file between 1 byte and 100 MB.',
  '媒体在复制时超过 100 MB。': 'Media exceeded 100 MB while copying.', '源媒体在复制期间发生变化，请重新插入。': 'The source media changed while copying. Insert it again.', '无法分配可用的媒体文件名。': 'Cannot assign an available media filename.', '媒体在导出期间发生变化。': 'The media changed during export.', '封面超过嵌入上限。': 'The poster exceeds the embedding limit.', '超出离线媒体嵌入上限（单文件 8 MB，总计 24 MB）。': 'Offline media exceeds the embedding limit (8 MB per file, 24 MB total).',
  '图片上传': 'Image upload', '尚未配置': 'Not configured', '已配置': 'Configured', '命令预设': 'Command preset', '参数数组（JSON）': 'Arguments (JSON array)', '单图超时（秒）': 'Timeout per image (seconds)', '值': 'Value',
  '尚未配置上传器；请选择程序并保存参数后，再明确点击上传。': 'Choose an upload program and save its arguments before clicking Upload.', '请通过本机文件选择器选择 PicGo、PicList 或其他 CLI 程序。': 'Use the local file picker to choose PicGo, PicList or another CLI program.', '请选择真实可执行程序；.cmd/.bat 需要 shell，不能直接使用。Node CLI 请选 node.exe 并把脚本路径放入参数数组。': 'Choose a real executable. .cmd and .bat scripts require a shell and cannot run directly. For a Node CLI, choose node.exe and add the script path to the arguments array.',
  '设置已保存。只有点击“上传所选图片”才会执行上传器。': 'Settings saved. The upload program runs only when you click “Upload selected images”.', '只能上传当前文档引用的已授权本地图片。': 'Only authorized local images referenced by this document can be uploaded.', '当前窗口已有图片上传任务。': 'An image upload is already running in this window.', '请等待上传任务结束后检查结果。': 'Wait for the upload to finish before reviewing results.',
  '等待上传': 'Waiting to upload', '上传中': 'Uploading', '上传成功，等待选择应用': 'Uploaded; choose whether to apply', '成功 · 等待检查': 'Success · Awaiting review', '上传进行中…': 'Uploading…', '上传进度': 'Upload progress', '上传结果': 'Upload results', '已应用': 'Applied', '失败': 'Failed', '取消全选': 'Deselect all',
  '准备冻结副本': 'Preparing frozen copies', '正在冻结 {value1}…': 'Freezing {value1}…', '正在上传 {value1}…': 'Uploading {value1}…', '冻结期间图片发生变化，已停止该图片上传。': 'The image changed while freezing its copy. Its upload was stopped.', '本批冻结图片总量超过 256 MB。': 'Frozen images in this batch exceed 256 MB.',
  '上传任务完成，请逐项选择要应用的结果。': 'Upload finished. Review each result and choose which to apply.', '已取消；成功结果保留供检查。': 'Cancelled. Successful results are kept for review.', '逐项检查成功 URL；失败和取消项不会修改文档。': 'Review each successful URL. Failed and cancelled items do not change the document.',
  '应用 {value1} 的上传结果': 'Apply upload result for {value1}', '原图在上传后发生变化：{value1}。请刷新结果并明确选择上传时的冻结版本。': 'The original image changed after upload: {value1}. Refresh the results and explicitly select the frozen version used for upload.', '只能应用已成功且经过检查的图片结果。': 'Only successful, reviewed image results can be applied.', '上传结果不属于当前窗口和文档。': 'These upload results belong to a different window or document.',
  '已应用 {value1} 张图片的上传 URL，更新 {value2} 处图片引用；本地原件保留，可通过文档撤销恢复。': 'Applied upload URLs for {value1} images and updated {value2} references. Local originals are kept; undo in the document to restore them.',
  '上传器不是普通程序文件。': 'The upload program is not a regular executable file.', '无法启动上传器：{value1}': 'Cannot start upload program: {value1}', '上传器失败（{value1}）：{value2}': 'Upload program failed ({value1}): {value2}', '上传器没有返回可用的 HTTP(S) 图片 URL。': 'The upload program did not return a usable HTTP(S) image URL.', '上传器返回多个不同 URL，无法安全确定当前图片的结果。': 'The upload program returned multiple different URLs. The result for this image cannot be determined safely.',
  '上传器诊断超过限制。': 'Upload program diagnostics exceeded the limit.', '上传器输出超过限制。': 'Upload program output exceeded the limit.', '上传已取消。': 'Upload cancelled.', '上传超时。': 'Upload timed out.', '图片上传操作未完成。': 'The image upload operation did not finish.', '无法开始上传。': 'Cannot start upload.', '无法读取上传器设置。': 'Cannot read upload settings.', '未指定源文件': 'No source file specified',
  '已导入：{value1}': 'Imported: {value1}', 'notes/新文档.md': 'notes/new-document.md',
  '{name}（.{extension}）': '{name} (.{extension})', 'HTML 源码': 'HTML source', '嵌入的媒体数据': 'Embedded media data',
  '上传图片…': 'Upload images…', '上传此图片…': 'Upload this image…', '上传程序': 'Upload program', '本机上传器设置': 'Local upload program settings', '选择上传程序…': 'Choose upload program…', '清除程序选择': 'Clear program selection', '自定义 CLI': 'Custom CLI',
  '本地原件保留 · 应用 URL 可通过文档撤销': 'Local originals are kept · Applied URLs support document undo', '关闭面板（上传继续）': 'Close panel (upload continues)',
  '选择本机上传器，把图片上传后逐项检查，再应用到文档。': 'Choose a local upload program, review each uploaded image, then apply the results to your document.',
  '每项是独立参数，{file} 替换为当前图片的冻结副本路径。Windows 的 .cmd/.bat 不能直接使用；Node CLI 请选 node.exe，并把脚本路径作为首个参数。': 'Each entry is a separate argument. {file} is replaced with the frozen image copy’s path. Windows .cmd and .bat scripts cannot run directly. For a Node CLI, choose node.exe and use the script path as the first argument.',
  'PicGo / PicList 预设使用 upload {file}。上传服务、账户和凭证请在对应上传器中设置。选择程序、保存设置和打开此窗口都不会上传。': 'PicGo / PicList presets use upload {file}. Configure services, accounts and credentials in the upload program. Choosing a program, saving settings or opening this panel does not upload anything.',
  '保存上传器设置': 'Save upload settings', '选择本地图片': 'Select local images', '上传所选图片': 'Upload selected images', '取消上传': 'Cancel upload',
  '当前文档没有可上传的本地图片。远程图片、缺失资源和越界路径不会上传。': 'This document has no local images available for upload. Remote images, missing files and paths outside authorized folders are excluded.',
  '仅上传当前文档引用的已授权图片。单图最多 25 MB，每批最多 100 张、256 MB。原图发生变化会停止该项或要求重新检查。': 'Uploads only authorized images referenced by this document. Limits: 25 MB per image, 100 images and 256 MB per batch. Changes to an original stop that item or require another check.',
  '参数尚未保存，请先保存设置再开始上传。': 'Save your updated settings before uploading.', '刷新原图检查': 'Refresh original image check',
  '原图已改变。勾选此项表示明确使用上传时的冻结版本；当前本地原件仍保留。': 'The original changed. Selecting this item explicitly uses the frozen version from the upload. The current local original is kept.',
  '仅应用你勾选的成功结果，替换当前文档全部对应图片引用。共享的普通文档链接保持原地址。': 'Applies only selected successful results to all matching image references in this document. Ordinary document links retain their original addresses.',
  '应用所选 URL（{count}）': 'Apply selected URLs ({count})', '导入主题': 'Imported theme', '从本地 CSS 文件导入': 'Imported from a local CSS file', '新主题': 'New theme',
  '无法准备上传，文档与本地图片保持原样。': 'Cannot prepare upload. The document and local images are unchanged.', '无法创建安全的上传暂存目录。': 'Cannot create a safe upload staging folder.', '读取期间图片路径发生变化。': 'The image path changed while reading.',
  '参数不能包含空字符或换行。': 'Arguments cannot contain null characters or line breaks.', '参数数组必须包含 {file} 占位符。': 'The arguments array must contain a {file} placeholder.',
  '媒体路径没有得到授权。': 'The media path is not authorized.', '图片路径没有得到授权。': 'The image path is not authorized.', '图片无法打开：{reason}': 'Cannot open image: {reason}', '媒体无法打开：{reason}': 'Cannot open media: {reason}', '视频封面无法打开：{reason}': 'Cannot open video poster: {reason}',
  '无法播放此媒体。源文件与 HTML 源码已保留，可检查路径或浏览器支持的编码。': 'Cannot play this media. The source file and HTML source are kept. Check the path or whether the browser supports its encoding.',
  '远程媒体未加载。点击后可使用播放器控件播放。': 'Remote media has not loaded. Click to load it, then use the player controls.', '正在解析远程媒体…': 'Resolving remote media…', '媒体已加载，可使用播放器控件播放。': 'Media loaded. Use the player controls to play it.', '加载远程媒体': 'Load remote media',
  '音频引用：{sources}（在原文档中播放）': 'Audio reference: {sources} (play in the original document)', '音频引用：{sources}（源媒体需单独提供）': 'Audio reference: {sources} (provide the source media separately)',
  '视频引用：{sources}（在原文档中播放）': 'Video reference: {sources} (play in the original document)', '视频引用：{sources}（源媒体需单独提供）': 'Video reference: {sources} (provide the source media separately)',
  '已插入音视频：{name}': 'Audio / video inserted: {name}', '插入音视频失败：{reason}': 'Failed to insert audio / video: {reason}', '请先保存文档后再引用本地音视频。': 'Save the document before referencing local audio or video.',
  '已插入 {count} 个本地资源': 'Inserted {count} local resources', '已导出：{path}；{count} 处媒体资源以引用说明保留': 'Exported: {path}; {count} media resources retained as reference descriptions',
  '已应用 {count} 张图片的上传结果，本地原件保留': 'Applied upload results for {count} images; local originals are kept', '所选资源为空或超过大小限制。': 'The selected resource is empty or exceeds the size limit.',
  '插入期间文档发生变化，资源副本已保留，请重新插入。': 'The document changed during insertion. Resource copies were kept; insert them again.', '插入资源失败，已复制的文件仍保留：{reason}': 'Failed to insert resources. Copied files were kept: {reason}',
  '文档在操作期间发生变化，请重新检查后应用。': 'The document changed during the operation. Check again before applying.', '文档已关闭或保存位置改变，请重新打开图片上传。': 'The document closed or its save location changed. Reopen image upload.',
  '上传文档图片': 'Upload document images', '插入音视频': 'Insert audio / video',
  '使用本地资源前需要先保存文档': 'Save the document before using local resources', 'Markdown 源码编辑器': 'Markdown source editor',
  '图片不是授权目录内受支持的普通图片文件。': 'The image is not a supported regular image file inside an authorized folder.', '封面超过预览上限。': 'The poster exceeds the preview limit.',
  '开始写作…': 'Start writing…', '选择图片': 'Choose image', '确认': 'Confirm', '或粘贴图片链接': 'Or paste an image link', '图片说明': 'Image description',
  '图表预览': 'Diagram preview', '正在渲染…': 'Rendering…', '编辑源码': 'Edit source', '隐藏源码': 'Hide source',
  '搜索代码语言': 'Search code languages', '复制代码': 'Copy code', '未找到语言': 'No languages found', '添加标题后将在这里显示目录': 'Add headings to display a table of contents here',
  '图片引用：{source}（源图片需单独提供）': 'Image reference: {source} (provide the source image separately)',
  '已导出：{path}；{count} 处资源以引用说明保留': 'Exported: {path}; {count} resources retained as reference descriptions',
}
