import assert from 'node:assert/strict'
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { _electron as electron } from 'playwright'

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)))
const temporary = await mkdtemp(path.join(tmpdir(), 'penlume-layout-'))
const workspace = path.join(temporary, 'notes')
const artifacts = path.join(root, process.env.TTYPORA_UI_ARTIFACTS ?? 'artifacts/ui-v0.12')
const variant = process.env.TTYPORA_PACKAGED_EXE ? 'packaged' : 'source'
const note = path.join(workspace, '写作示例.md')
const text = '# 让文字成为主角\n\n安静的界面，让注意力回到正在写的这一段。\n\n## 一个清晰的工作区\n\n正文、侧栏与预览各有自己的位置。窗口变小时，面板会自动调整，不挤压内容。\n\n- 菜单和快捷键随时可用\n- 拖动分隔线调整比例\n- 字号与界面缩放分别设置\n\n> 留下必要的工具，也留出写作的空间。\n'
await mkdir(workspace); await mkdir(artifacts, { recursive: true }); await writeFile(note, text)
let app, page
const errors = [], checks = []
try {
  const flags = ['--disable-gpu', '--disable-backgrounding-occluded-windows', '--disable-background-timer-throttling', '--disable-renderer-backgrounding']
  app = await electron.launch({ ...(process.env.TTYPORA_PACKAGED_EXE ? { executablePath: path.resolve(root, process.env.TTYPORA_PACKAGED_EXE) } : {}), args: process.env.TTYPORA_PACKAGED_EXE ? flags : [...flags, '.'], cwd: root, env: { ...process.env, TTYPORA_SMOKE_TEST: '1', TTYPORA_USER_DATA_PATH: temporary, TTYPORA_SMOKE_WORKSPACE_PATH: workspace } })
  page = await app.firstWindow(); page.on('pageerror', (error) => errors.push(String(error)))
  await page.emulateMedia({ colorScheme: 'light', reducedMotion: 'reduce' })
  const command = (value) => app.evaluate(({ BrowserWindow }, value) => BrowserWindow.getAllWindows()[0].webContents.send('app:command', value), value)
  const size = (width, height = 760) => app.evaluate(({ BrowserWindow }, dimensions) => { const win = BrowserWindow.getAllWindows()[0]; win.setSize(...dimensions); win.show(); win.focus() }, [width, height])
  const reload = async () => {
    await page.reload(); await page.locator('.ProseMirror').waitFor()
    // Recovery is independent of layout. A pending draft can legitimately be
    // offered after restart; dismiss its public dialog before using the header.
    const recovery = page.getByRole('dialog', { name: '发现恢复草稿', exact: true })
    await recovery.waitFor({ timeout: 1500 }).catch((error) => { if (error.name !== 'TimeoutError') throw error })
    if (await recovery.isVisible()) await recovery.getByLabel('关闭', { exact: true }).click()
  }
  await size(1180)
  await page.locator('.ProseMirror').waitFor()
  assert.equal(await page.locator('.sidebar-panel').count(), 0)
  assert.equal(await page.locator('.editor-toolbar').count(), 0)
  assert.equal(await page.locator('.activity-rail').count(), 0)
  assert.equal(await page.locator('.document-tabs').isVisible(), false)
  await command('open-workspace'); await page.locator('.file-tree').getByTitle(note, { exact: true }).click()
  await page.getByLabel('关闭侧栏', { exact: true }).click()
  await page.locator('.ProseMirror h1').waitFor()
  assert.equal(await page.locator('.ProseMirror h1').evaluate((heading) => getComputedStyle(heading).marginTop), '0px')
  await page.screenshot({ path: path.join(artifacts, `${variant}-1180-writing.png`) })
  checks.push('Fresh default has one compact header, no rail, no formatting row, and hidden single tab')

  await command('show-outline')
  const sidebar = page.getByRole('separator', { name: '调整侧栏宽度', exact: true })
  await sidebar.waitFor(); const box = await sidebar.boundingBox()
  await page.mouse.move(box.x + box.width / 2, box.y + 80); await page.mouse.down(); await page.mouse.move(box.x + 80, box.y + 80, { steps: 8 }); await page.mouse.up()
  await page.waitForFunction(() => document.querySelector('.sidebar-panel').getBoundingClientRect().width > 300)
  await sidebar.focus(); await page.keyboard.press('Enter')
  await page.waitForFunction(() => Math.abs(document.querySelector('.sidebar-panel').getBoundingClientRect().width - 240) < 1)
  await page.keyboard.press('ArrowRight'); await page.waitForFunction(() => Math.abs(document.querySelector('.sidebar-panel').getBoundingClientRect().width - 250) < 1)
  await size(760)
  await page.locator('.workspace-layout--overlay').waitFor()
  assert.equal(await page.locator('.sidebar-backdrop').count(), 1)
  assert.ok((await page.locator('.workbench').boundingBox()).width > 700)
  await page.locator('.sidebar-backdrop').click({ position: { x: 620, y: 100 } })
  assert.equal(await page.locator('.sidebar-panel').count(), 0)
  checks.push('Sidebar drag, keyboard reset/resize, drawer layout, and click-outside close')

  await size(1180); await command('toggle-split-mode'); await page.locator('.live-preview').waitFor()
  await page.frameLocator('.live-preview iframe').locator('h1').waitFor()
  const split = page.getByRole('separator', { name: '调整源码与预览比例', exact: true })
  await split.focus(); await page.keyboard.press('ArrowRight'); await page.keyboard.press('ArrowRight')
  await page.waitForFunction(() => JSON.parse(localStorage.getItem('ttypora.layout')).splitRatio === 52)
  await size(640, 500); await page.locator('.editor-panes--stacked').waitFor()
  assert.equal(await split.getAttribute('aria-orientation'), 'horizontal')
  await split.focus(); await page.keyboard.press('ArrowDown')
  await page.waitForFunction(() => JSON.parse(localStorage.getItem('ttypora.layout')).splitRatio === 53)
  await page.screenshot({ path: path.join(artifacts, `${variant}-640-stacked.png`) })
  await size(1180); await page.waitForFunction(() => !document.querySelector('.editor-panes').classList.contains('editor-panes--stacked'))
  assert.equal(await split.getAttribute('aria-valuenow'), '53')
  await page.screenshot({ path: path.join(artifacts, `${variant}-1180-split.png`) })
  checks.push('Split ratio persists across side-by-side and stacked layouts')

  await command('font-size-up'); await page.waitForFunction(() => JSON.parse(localStorage.getItem('ttypora.preferences')).fontSize === 18)
  await command('interface-zoom-in'); await page.waitForFunction(() => JSON.parse(localStorage.getItem('ttypora.preferences')).interfaceZoom === 110)
  await page.waitForFunction(() => window.innerWidth < 1100)
  assert.ok(Math.abs(await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].webContents.getZoomFactor()) - 1.1) < 0.01)
  await command('layout-settings'); await page.getByRole('dialog', { name: '布局与尺寸' }).waitFor()
  await page.getByRole('button', { name: '宽屏', exact: true }).click()
  await page.getByLabel('显示格式工具栏', { exact: true }).check()
  await page.getByRole('button', { name: '完成', exact: true }).click()
  await page.locator('.editor-toolbar').waitFor()
  await reload()
  assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('ttypora.layout')).splitRatio), 53)
  assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('ttypora.preferences')).contentWidth), 1120)
  assert.ok(Math.abs(await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].webContents.getZoomFactor()) - 1.1) < 0.01)
  await command('interface-zoom-reset'); await command('font-size-reset')
  await page.getByLabel('布局与尺寸', { exact: true }).click()
  await page.getByRole('button', { name: '重置布局与尺寸', exact: true }).click()
  await page.getByLabel('显示格式工具栏', { exact: true }).uncheck()
  await page.getByRole('button', { name: '完成', exact: true }).click()
  await command('open-workspace'); await page.locator('.file-tree').getByTitle(note, { exact: true }).click()
  await command('toggle-sidebar')
  await page.locator('.ProseMirror h1').waitFor()
  assert.ok((await page.locator('.ProseMirror').boundingBox()).width > 800)
  checks.push('Text size, actual Electron zoom, width presets and toolbar are separate and persistent; reset restores geometry')
  await size(640, 420)
  await command('layout-settings')
  const font = page.getByLabel('字号', { exact: true }), widthInput = page.getByLabel('正文宽度', { exact: true })
  const typeNumber = async (input, value) => { await input.focus(); await page.keyboard.press('Control+A'); await input.pressSequentially(value) }
  await typeNumber(font, '24')
  assert.equal(await font.inputValue(), '24')
  await page.keyboard.press('Tab')
  await page.waitForFunction(() => JSON.parse(localStorage.getItem('ttypora.preferences')).fontSize === 24)
  await typeNumber(widthInput, '600'); await page.keyboard.press('Enter')
  await page.waitForFunction(() => JSON.parse(localStorage.getItem('ttypora.preferences')).contentWidth === 600)
  await widthInput.fill(''); await page.keyboard.press('Tab')
  assert.equal(await widthInput.inputValue(), '600')
  await typeNumber(font, '100'); await page.keyboard.press('Enter')
  await page.waitForFunction(() => JSON.parse(localStorage.getItem('ttypora.preferences')).fontSize === 32)
  await typeNumber(page.getByLabel('界面缩放（%）', { exact: true }), '150'); await page.keyboard.press('Enter')
  await page.waitForFunction(() => window.innerWidth < 440)
  await page.evaluate(() => new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(resolve))))
  const footerVisible = () => page.evaluate(() => {
    const footer = document.querySelector('.modal__footer').getBoundingClientRect()
    const body = document.querySelector('.modal__body')
    return footer.top >= 0 && footer.bottom <= window.innerHeight && footer.left >= 0 && footer.right <= window.innerWidth && body.scrollHeight > body.clientHeight
  })
  assert.equal(await footerVisible(), true)
  const panelCapture = await app.evaluate(async ({ BrowserWindow }) => (await BrowserWindow.getAllWindows()[0].webContents.capturePage()).toPNG().toString('base64'))
  await writeFile(path.join(artifacts, `${variant}-640-size-panel-150.png`), Buffer.from(panelCapture, 'base64'))
  await page.getByRole('button', { name: '完成', exact: true }).click()
  await command('preferences'); await page.getByRole('dialog', { name: '偏好设置', exact: true }).waitFor()
  assert.equal(await footerVisible(), true)
  await typeNumber(page.getByLabel('行高', { exact: true }), '1.8'); await page.keyboard.press('Tab')
  await page.waitForFunction(() => JSON.parse(localStorage.getItem('ttypora.preferences')).lineHeight === 1.8)
  await typeNumber(page.getByLabel('缩进宽度', { exact: true }), '2.5'); await page.keyboard.press('Tab')
  await page.waitForFunction(() => JSON.parse(localStorage.getItem('ttypora.preferences')).tabSize === 3)
  await typeNumber(page.getByLabel('自动保存间隔（秒）', { exact: true }), '30.5'); await page.keyboard.press('Tab')
  await page.waitForFunction(() => JSON.parse(localStorage.getItem('ttypora.preferences')).autoSaveSeconds === 31)
  await page.getByRole('button', { name: '完成', exact: true }).click()
  await reload()
  assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('ttypora.preferences')).lineHeight), 1.8)
  assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('ttypora.preferences')).interfaceZoom), 150)
  await command('layout-settings'); await page.getByRole('button', { name: '重置布局与尺寸', exact: true }).click()
  await page.getByRole('button', { name: '完成', exact: true }).click()
  await page.waitForFunction(() => window.innerWidth > 600)
  assert.equal(await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].webContents.getZoomFactor()), 1)
  checks.push('Number fields accept sequential typing, decimal values, empty recovery and bounds on commit; integer preferences remain valid after reload; footer stays reachable at 640x420 and 150% zoom')
  for (const width of [640, 760, 980, 1180]) {
    await size(width)
    await page.waitForFunction(() => document.documentElement.scrollWidth <= window.innerWidth)
    const title = await page.locator('.workspace-header .document-title').boundingBox(), tools = await page.locator('.toolbar__group--end').boundingBox()
    assert.ok(title.x + title.width <= tools.x + 1)
  }
  await page.emulateMedia({ colorScheme: 'dark', reducedMotion: 'reduce' })
  await size(760); await page.screenshot({ path: path.join(artifacts, `${variant}-760-dark.png`) })
  assert.equal(await readFile(note, 'utf8'), text)
  assert.deepEqual(errors, [])
  checks.push('640/760/980/1180 widths without horizontal overflow or header overlap; original file bytes preserved')
  console.log(checks.join('\n'))
} catch (error) {
  if (page && !page.isClosed()) {
    console.error(await page.evaluate(() => ({ inner: [innerWidth, innerHeight], modal: document.querySelector('.modal')?.getBoundingClientRect().toJSON(), footer: document.querySelector('.modal__footer')?.getBoundingClientRect().toJSON(), bodyHeight: document.querySelector('.modal__body')?.clientHeight, bodyScroll: document.querySelector('.modal__body')?.scrollHeight })))
    const failureCapture = await app.evaluate(async ({ BrowserWindow }) => (await BrowserWindow.getAllWindows()[0].webContents.capturePage()).toPNG().toString('base64')).catch(() => null)
    if (failureCapture) await writeFile(path.join(artifacts, `${variant}-layout-failure.png`), Buffer.from(failureCapture, 'base64'))
  }
  throw error
} finally {
  if (app) await app.close()
  const resolved = path.resolve(temporary)
  assert.equal(path.dirname(resolved), path.resolve(tmpdir()))
  assert.ok(path.basename(resolved).startsWith('penlume-layout-'))
  await rm(resolved, { recursive: true, force: true })
}
await writeFile(path.join(artifacts, `${variant}-layout-verification.json`), JSON.stringify({ completedAt: new Date().toISOString(), checks, errors }, null, 2))
